## Predictive Modeling Approach for Employee Salaries Estimations Based on Linear Regression Analysis 


### 1. Introduction

In this notebook we will explore the linear regression model for learning predictive modeling. Linear Regression is a very simple machine learning algorithm for finding the relationship between two continuous variables.

In this study, we have determined the linear relationship between the numbers of years experience of the employee in the company and the salary of an employee in the current time.

### 2. Import the Libraries

#### 2.1. NumPy 
Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np               

#### 2.2. Pandas
Pandas is a software library written for the Python programming language for data processing, data manipulation and data analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series.

In [2]:
import pandas as pd               

#### 2.3. Matplotlib
Matplotlib is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms.

In [3]:
import matplotlib.pyplot as plt 

### 3. Import the dataset

Salary_Data.csv file is obtained from the Kaggle.com at
https://www.kaggle.com/karthickveerakumar/salary-data-simple-linear-regression/version/1


In [4]:
dataset = pd.read_csv('Salary_Data.csv')

#### 3.1. Loading the dataset in numpy matrix

In [5]:
X = dataset.iloc[:,:-1].values   
y = dataset.iloc[:,-1].values     

#### 3.2. Dataset columns
Salary_Data.csv file consists of 2 columns, first one is "YearsExperience" and is used as independent variable "X" and second one is "Salary" used as dependent variable "y".

In [6]:
print(dataset)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0


### 4. Split the dataset into training and testing  set 

When you’re working on a model and want to train it, you obviously have a dataset. But after training, we have to test the model on some test dataset. For this, we need a dataset which is different from the training set you used earlier. But it might not always be possible to have so much data during the development phase.

In such cases, the obviously solution is to split the dataset you have into two sets, one for training and the other for testing; and you do this before you start training your model.

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
print(X_train)

[[ 9.6]
 [ 4. ]
 [ 5.3]
 [ 7.9]
 [ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]


In [9]:
print(y_train)

[112635.  55794.  83088. 101302.  56642.  66029.  64445.  61111. 113812.
  91738.  46205. 121872.  60150.  39891.  81363.  93940.  57189.  54445.
 105582.  43525.  39343.  98273.  67938.  56957.]


In [10]:
print(X_test)

[[ 1.5]
 [10.3]
 [ 4.1]
 [ 3.9]
 [ 9.5]
 [ 8.7]]


In [11]:
print(y_test)

[ 37731. 122391.  57081.  63218. 116969. 109431.]


### 5. Linear Regression Model 
we import our linear regression model from sklearn library. Sklearn is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms.

In [12]:
from sklearn.linear_model import LinearRegression

#### 5.1.  Initialisation of linear regression
Create an object called linear_model of Linear Regression class and fit the training data into it.

In [13]:
linear_model = LinearRegression()

#### 5.2. Inserting the train data in model for training purpose

In [14]:
linear_model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

#### 5.3. Prediction Results
Since the model has been trained with the training data now we will do predictions with the testing data. Y_pred will give the predicted values of test dataset.

In [15]:
y_pred = linear_model.predict(X_test)
print(y_pred)

[ 40748.96184072 122699.62295594  64961.65717022  63099.14214487
 115249.56285456 107799.50275317]


#### 5.4. Variance regression score function

In [16]:
from sklearn.metrics import explained_variance_score
explained_variance_score(y_test, y_pred)

0.9897037514693541

#### 5.5. Mean absolute error regression loss

In [17]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

2446.1723690465055

#### 5.6. Mean squared error regression loss

In [18]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred) 

12823412.298126549

#### 5.7. Mean squared logarithmic error regression loss

In [19]:
from sklearn.metrics import mean_squared_log_error
mean_squared_log_error(y_test, y_pred)

0.0038500332431183216

#### 5.8. Median absolute error regression loss

In [20]:
from sklearn.metrics import median_absolute_error
median_absolute_error(y_test, y_pred)

1675.4671961362037

#### 5.9. R2 (coefficient of determination) regression score function

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred) 

0.988169515729126

#### 5.10. Plotting the graph for training data

In [22]:
plt.scatter(X_train,y_train, color= 'red')
plt.plot(X_train, linear_model.predict(X_train), color= 'blue' )
plt.title('Salary Prediction')
plt.xlabel('Years Experience')
plt.ylabel('Salary')
plt.show()

#### 5.11. Plotting the graph for testing data

In [23]:
plt.scatter(X_test, y_test, color='red')
plt.plot(X_test, y_pred, color='blue')
plt.title("Salary Prediction")
plt.xlabel('Years Experience')
plt.ylabel('Salary')
plt.show()